### ISSUE TITLE
Questions about the uploaded sparse $\theta_i$

### ISSUE THREAD

**Issue by xuanyx** [yxdyc/pFedGate#1]
In Algorithm 1, the authors generate the corresponding gating weights for each batch (line 5).  My question is that if the gating weights are different between batches, then the blocks selected during the masking phase may be different.  So how to get the final uploaded mask? Is it the intersection or union of the masks of each batch? If is a union, the worst case is uploading the full model, which can not improve the communication efficiency.

**Comment by yxdyc** [comment]
Hi, we train the models using the sparse masks triggered by each batch for implementation convenience (the commonly used per-batch back-propagation manner), which corresponds to the union operation. So you're right that the worst case will be a full model without communication efficiency improvement. However, we empirically find that the local data batches within a client usually share some similarities in the view of triggered masks and the worst case doesn't happen often (a more detailed discussion can be found in Appendix F). 

One more word, your question is insightful! By restricting the final mask with *intersection* operation, we can provide a worst-case guarantee with the specified sparsity value. It may affect the training stability and waste some training samples (as the non-overlap parts will be discarded), while is promising and worthy to explore. Thanks for your interest!

**Comment by xuanyx** [comment]
Thanks a lot for your prompt reply! 
Thanks again for your great work and for releasing the code.
